#!/usr/bin/env bash

# Get current directory
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
EXEC_FILE="./src/ademco.py"
CONFIG_FILE="envisakit-config.json"

# Issue command
if [ -f "$DIR/$CONFIG_FILE" ] ; then
	$EXEC_FILE $@
	exit $?
else
	echo "Set up your $CONFIG_FILE file before running this command."
	exit 1
fi

popd &> /dev/null
